# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
import socket
import time
import port_forward_3
#from fsplit.filesplit import Filesplit



#fs=Filesplit()




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(425, 455)
        MainWindow.setAcceptDrops(True)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 129, 91, 73))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(30, 130, 281, 71))
        self.textEdit.setObjectName("textEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(32, 26, 131, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(32, 113, 220, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(32, 6, 131, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(32, 212, 131, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(32, 236, 131, 16))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(32, 284, 381, 20))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(32, 269, 381, 20))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(32, 248, 480, 31))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(32, 327, 47, 13))
        self.label_12.setObjectName("label_12")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(87, 324, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(87, 352, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(32, 354, 47, 13))
        self.label_13.setObjectName("label_13")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(87, 380, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(32, 380, 51, 16))
        self.label_14.setObjectName("label_14")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 322, 101, 81))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(32, 32, 371, 41))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(32, 62, 291, 41))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(79, 91, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(32, 48, 371, 41))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(32, 300, 390, 20))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(32, 93, 47, 13))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(290, 100, 111, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "P2PFileTransfer"))
        self.pushButton.setText(_translate("MainWindow", "Send"))
        self.pushButton.clicked.connect(self.sendFile)
        self.label_4.setText(_translate("MainWindow", "Instructions:"))
        self.label_5.setText(_translate("MainWindow", "Drop the file here:"))
        self.label_6.setText(_translate("MainWindow", "Send:"))
        self.label_7.setText(_translate("MainWindow", "Receive:"))
        self.label_8.setText(_translate("MainWindow", "Instructions:"))
        self.label_9.setText(_translate("MainWindow", "you just give it a name and extension and you are done!"))
        self.label_10.setText(_translate("MainWindow", "sending peer(there are lots of tutorials on internet) then"))
        self.label_11.setText(_translate("MainWindow", "For receiving a file you have to paste the public ip of the"))
        self.label_12.setText(_translate("MainWindow", "IP:"))
        self.label_13.setText(_translate("MainWindow", "Filename:"))
        self.label_14.setText(_translate("MainWindow", "extension:"))
        self.pushButton_2.setText(_translate("MainWindow", "Receive"))
        self.pushButton_2.clicked.connect(self.receiveFile)
        self.label.setText(_translate("MainWindow", "Specify the buffer(leave blank for default)(client has to have the same) "))
        self.label_2.setText(_translate("MainWindow", "Drop the file and hit send"))
        self.label_3.setText(_translate("MainWindow", "have the same buffer)(max suggested buffer 256000) "))
        self.label_15.setText(_translate("MainWindow", "remember to specify the same buffer as the server above"))
        self.label_16.setText(_translate("MainWindow", "Buffer:"))
        self.pushButton_3.setText(_translate("MainWindow", "Localhost"))
        self.pushButton_3.clicked.connect(self.localHostClick)
        self.localHost=False

    


    def localHostClick(self):
        
        if self.localHost==False:
            self.localHost=True
        else:
            self.localHost=False
        self.textEdit.setText("localHost set to: "+str(self.localHost))


    def receiveFile(self):
        
        startRecv=time.perf_counter()
        bufferStr=self.lineEdit_4.text()
        if bufferStr=="":
            buffer=32000
        else:
            buffer=int(bufferStr)
        s = socket.socket()             # Create a socket object
        host = self.lineEdit.text() #Ip address that the TCPServer  is there
        port = 25575                     # Reserve a port for your service every new transfer wants a new port or you must wait.

        s.connect((host, port))
        welcomemsg="Hello server!"
        s.send(bytearray(welcomemsg,"utf-8"))

        with open('received_file', 'wb') as f:
            print('file opened')
            #self.textEdit.append('receiving data...')
            while True:
                
                data = s.recv(buffer)
                #print('data=%s', (data))
                if not data:
                    break
                # write data to a file
                f.write(data)

        f.close()
        endRecv=time.perf_counter()
        finalTimeRecv=endRecv-startRecv
        self.textEdit.append('Successfully got the file in '+str(round(finalTimeRecv,3))+"s")
        s.close()
        print('connection closed')
        filename=self.lineEdit_2.text()
        ext=self.lineEdit_3.text()
        os.rename("received_file",filename+ext)


    def sendFile(self):
        if self.localHost==False:
            openPort = port_forward_3.EnablePort(25575)
        #openPort = portforwardlib.forwardPort(25575,25575,"","",False,"TCP","","P2Pfiletranfer","")
        else:
            xd=1
        filepath= self.textEdit.toPlainText()
        filepath=filepath.replace("file:///","")
        bufferStr=self.lineEdit_4.text()
        if bufferStr=="":
            buffer=32000
        else:
            buffer=int(bufferStr)

        port = 25575                    # Reserve a port for your service every new transfer wants a new port or you must wait.
        s = socket.socket()             # Create a socket object
        host = ""   # Get local machine name
        s.bind((host, port))            # Bind to the port
        s.listen(5)                     # Now wait for client connection.
       

        self.textEdit.append('Server listening....')
        i=0
        

        while i==0:
            conn, addr = s.accept()     # Establish connection with client.
            self.textEdit.append('Got connection from' + str(addr))
            startSend=time.perf_counter()

            data = conn.recv(buffer)
            #self.textEdit.setText('Server received' + str(repr(data)))

            filename=filepath #In the same folder or path is this file running must the file you want to tranfser to be
            f = open(filename,'rb')
            l = f.read(buffer)
            #self.textEdit.append('Sending file ')
            while (l):
                conn.send(l)
                
                l = f.read(buffer)
            f.close()
            endSend=time.perf_counter()

            finalTimeSend=endSend-startSend

            self.textEdit.append('Done sending in '+str(round(finalTimeSend,3))+"s")
           
            conn.close()
            if self.localHost==False:
                closePort=port_forward_3.DisablePort(25575)
            else:
               xd=1
            i=1
    
            




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
