# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdvancedOption.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    #def __init__(self):
    #    Form = QtWidgets.QWidget()
    #    self.setupUi(Form)
    #    Form.show()
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(160, 140, 71, 31))
        self.checkBox.setObjectName("checkBox")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(100, 170, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(100, 140, 51, 31))
        self.label.setObjectName("label")
        #self.pushButton= QtWidgets.QPushButton(Form)
        #self.pushButton.setGeometry(QtCore.QRect(100,100,60,40))
        #self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox.setText(_translate("Form", "Encrypted"))
        self.label.setText(_translate("Form", "Password"))
       #  self.pushButton.clicked.connect(self.OnClick)

    def isEncrypted(self):
        isEncrypted=self.checkBox.isChecked()
        if isEncrypted==True:
            password=self.lineEdit.text()
        return isEncrypted,password
    #def OnClick(self):
     #   print(Ui_Form.isEncrypted(self))

#if __name__ == "__main__":
  #  import sys
   # app = QtWidgets.QApplication(sys.argv)
   # Form = QtWidgets.QWidget()
   # ui = Ui_Form()
   # ui.setupUi(Form)
   # Form.show()
   # sys.exit(app.exec_())

