# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HelpBoxtest.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_HelpMenu(object):
    def setupUi(self, HelpMenu):
        HelpMenu.setObjectName("HelpMenu")
        HelpMenu.resize(420, 312)
        HelpMenu.setMinimumSize(QtCore.QSize(420, 312))
        HelpMenu.setMaximumSize(QtCore.QSize(420, 312))
        self.horizontalLayout = QtWidgets.QHBoxLayout(HelpMenu)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        #TRANSLUSID BACK GROUND
        HelpMenu.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        HelpMenu.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        #----------------------------------------------------------#
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_7 = QtWidgets.QFrame(HelpMenu)
        self.frame_7.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 0, 0, 255), stop:0.620209 rgba(0, 0, 0, 255));\n"
"border-radius: 10px;\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setContentsMargins(4, 4, 4, 4)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Base_Frame = QtWidgets.QFrame(self.frame_7)
        self.Base_Frame.setEnabled(True)
        self.Base_Frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(42, 44, 111, 255), stop:0.620209 rgba(28, 29, 73, 255));\n"
"border-radius: 10px;\n"
"")
        self.Base_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Base_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Base_Frame.setObjectName("Base_Frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Base_Frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_title = QtWidgets.QFrame(self.Base_Frame)
        self.frame_title.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_title.setStyleSheet("Background-color: none;")
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_2.setContentsMargins(7, 7, 7, 7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_Usful = QtWidgets.QLabel(self.frame_title)
        self.label_Usful.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(20)
        self.label_Usful.setFont(font)
        self.label_Usful.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_Usful.setObjectName("label_Usful")
        self.verticalLayout_2.addWidget(self.label_Usful)
        self.verticalLayout.addWidget(self.frame_title)
        self.frame_2 = QtWidgets.QFrame(self.Base_Frame)
        self.frame_2.setStyleSheet("Background-color: none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_buffer = QtWidgets.QFrame(self.frame_2)
        self.frame_buffer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_buffer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_buffer.setObjectName("frame_buffer")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_buffer)
        self.verticalLayout_3.setContentsMargins(0, 0, 5, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_buffer = QtWidgets.QLabel(self.frame_buffer)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_buffer.setFont(font)
        self.label_buffer.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_buffer.setObjectName("label_buffer")
        self.verticalLayout_3.addWidget(self.label_buffer)
        self.label_buffer_2 = QtWidgets.QLabel(self.frame_buffer)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(10)
        self.label_buffer_2.setFont(font)
        self.label_buffer_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_buffer_2.setObjectName("label_buffer_2")
        self.verticalLayout_3.addWidget(self.label_buffer_2)
        self.label_buffer_3 = QtWidgets.QLabel(self.frame_buffer)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(10)
        self.label_buffer_3.setFont(font)
        self.label_buffer_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_buffer_3.setObjectName("label_buffer_3")
        self.verticalLayout_3.addWidget(self.label_buffer_3)
        self.label_buffer_4 = QtWidgets.QLabel(self.frame_buffer)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(10)
        self.label_buffer_4.setFont(font)
        self.label_buffer_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_buffer_4.setObjectName("label_buffer_4")
        self.verticalLayout_3.addWidget(self.label_buffer_4)
        self.label_buffer_5 = QtWidgets.QLabel(self.frame_buffer)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(10)
        self.label_buffer_5.setFont(font)
        self.label_buffer_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_buffer_5.setObjectName("label_buffer_5")
        self.verticalLayout_3.addWidget(self.label_buffer_5)
        self.horizontalLayout_2.addWidget(self.frame_buffer)
        self.frame_local_2 = QtWidgets.QFrame(self.frame_2)
        self.frame_local_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_local_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_local_2.setObjectName("frame_local_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_local_2)
        self.verticalLayout_4.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_local = QtWidgets.QFrame(self.frame_local_2)
        self.frame_local.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_local.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_local.setObjectName("frame_local")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_local)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_local = QtWidgets.QLabel(self.frame_local)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_local.setFont(font)
        self.label_local.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_local.setObjectName("label_local")
        self.verticalLayout_5.addWidget(self.label_local)
        self.label_local2 = QtWidgets.QLabel(self.frame_local)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(10)
        self.label_local2.setFont(font)
        self.label_local2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_local2.setObjectName("label_local2")
        self.verticalLayout_5.addWidget(self.label_local2)
        self.label_local1 = QtWidgets.QLabel(self.frame_local)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(10)
        self.label_local1.setFont(font)
        self.label_local1.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_local1.setObjectName("label_local1")
        self.verticalLayout_5.addWidget(self.label_local1)
        self.verticalLayout_4.addWidget(self.frame_local)
        self.frameIP = QtWidgets.QFrame(self.frame_local_2)
        self.frameIP.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameIP.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameIP.setObjectName("frameIP")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frameIP)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_IP = QtWidgets.QLabel(self.frameIP)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_IP.setFont(font)
        self.label_IP.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_IP.setObjectName("label_IP")
        self.verticalLayout_6.addWidget(self.label_IP)
        self.label_lp1 = QtWidgets.QLabel(self.frameIP)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(10)
        self.label_lp1.setFont(font)
        self.label_lp1.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_lp1.setObjectName("label_lp1")
        self.verticalLayout_6.addWidget(self.label_lp1)
        self.label_ip2 = QtWidgets.QLabel(self.frameIP)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(10)
        self.label_ip2.setFont(font)
        self.label_ip2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_ip2.setObjectName("label_ip2")
        self.verticalLayout_6.addWidget(self.label_ip2)
        self.verticalLayout_4.addWidget(self.frameIP)
        self.horizontalLayout_2.addWidget(self.frame_local_2)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.Base_Frame)
        self.frame_3.setStyleSheet("Background-color: none;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_7.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_8.setContentsMargins(0, 0, 5, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_file_name = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_file_name.setFont(font)
        self.label_file_name.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_file_name.setObjectName("label_file_name")
        self.verticalLayout_8.addWidget(self.label_file_name)
        self.label_file_name1 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(10)
        self.label_file_name1.setFont(font)
        self.label_file_name1.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_file_name1.setObjectName("label_file_name1")
        self.verticalLayout_8.addWidget(self.label_file_name1)
        self.label_file_name2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(10)
        self.label_file_name2.setFont(font)
        self.label_file_name2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_file_name2.setObjectName("label_file_name2")
        self.verticalLayout_8.addWidget(self.label_file_name2)
        self.horizontalLayout_4.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_9.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_extension = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_extension.setFont(font)
        self.label_extension.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_extension.setObjectName("label_extension")
        self.verticalLayout_9.addWidget(self.label_extension)
        self.label_file_extension1 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(10)
        self.label_file_extension1.setFont(font)
        self.label_file_extension1.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_file_extension1.setObjectName("label_file_extension1")
        self.verticalLayout_9.addWidget(self.label_file_extension1)
        self.label_file_extension1_2 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Sylfaen")
        font.setPointSize(10)
        self.label_file_extension1_2.setFont(font)
        self.label_file_extension1_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_file_extension1_2.setObjectName("label_file_extension1_2")
        self.verticalLayout_9.addWidget(self.label_file_extension1_2)
        self.horizontalLayout_4.addWidget(self.frame_6)
        self.verticalLayout_7.addWidget(self.frame_4)
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Button_return = QtWidgets.QPushButton(self.frame)
        self.Button_return.setMaximumSize(QtCore.QSize(90, 30))
        self.Button_return.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgba(166, 166, 166, 150);\n"
"}")
        self.Button_return.setObjectName("Button_return")
        self.horizontalLayout_3.addWidget(self.Button_return)
        self.verticalLayout_7.addWidget(self.frame)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout_5.addWidget(self.Base_Frame)
        self.horizontalLayout.addWidget(self.frame_7)

        self.retranslateUi(HelpMenu)
        QtCore.QMetaObject.connectSlotsByName(HelpMenu)

    def retranslateUi(self, HelpMenu):
        _translate = QtCore.QCoreApplication.translate
        HelpMenu.setWindowTitle(_translate("HelpMenu", "Form"))
        self.label_Usful.setText(_translate("HelpMenu", "Useful Information:"))
        self.label_buffer.setText(_translate("HelpMenu", "How to use the buffer"))
        self.label_buffer_2.setText(_translate("HelpMenu", "To use the Buffer you need to specify"))
        self.label_buffer_3.setText(_translate("HelpMenu", " a number betwen 8 and 256000 this"))
        self.label_buffer_4.setText(_translate("HelpMenu", " number must be the same in the host "))
        self.label_buffer_5.setText(_translate("HelpMenu", "and in te receiver."))
        self.label_local.setText(_translate("HelpMenu", "Use the LocalHost"))
        self.label_local2.setText(_translate("HelpMenu", "If you check the local host you will "))
        self.label_local1.setText(_translate("HelpMenu", "send the file via the local network."))
        self.label_IP.setText(_translate("HelpMenu", "Ip"))
        self.label_lp1.setText(_translate("HelpMenu", "Here you will have to put the public "))
        self.label_ip2.setText(_translate("HelpMenu", "IP and if you use local the IpV4."))
        self.label_file_name.setText(_translate("HelpMenu", "File Name "))
        self.label_file_name1.setText(_translate("HelpMenu", "Here you have to put the name which"))
        self.label_file_name2.setText(_translate("HelpMenu", "you want to save the file. "))
        self.label_extension.setText(_translate("HelpMenu", "Extension"))
        self.label_file_extension1.setText(_translate("HelpMenu", "Here you have to put the extension "))
        self.label_file_extension1_2.setText(_translate("HelpMenu", "which you want to save the file"))
        self.Button_return.setText(_translate("HelpMenu", "Exit"))
        #CLOSE BUTTON
        self.Button_return.clicked.connect(HelpMenu.close)
        #-----------------------------------------------------#


